[build]
  command = "ng build --configuration production"
  publish = "dist/Connection2Connection"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
